FROM us-west1-docker.pkg.dev/mlb-standings-001/cloud-run-source-deploy/custom-image-example AS custom-files

FROM us-west1-docker.pkg.dev/serverless-runtimes/google-22/runtimes/python312 

COPY --from=custom-files /opt/python /opt/python
COPY --from=custom-files /workspace /workspace

ENV PYTHONPATH=/opt/python/lib/python3.12/site-packages
ENV PATH=/opt/python/bin:$PATH

WORKDIR /workspace

# Run your application
CMD ["python", "start.py"]