FROM python:3.12 AS builder
# FROM us-west1-docker.pkg.dev/serverless-runtimes/google-22-full/runtimes/python312  # no pip

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Runtime stage
FROM python:3.12-slim

COPY --from=builder /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH

WORKDIR /app
COPY . .
# RUN python -m compileall .  # ? -f main.py

CMD ["sh", "-c", "exec functions-framework --target=hello --port=${PORT:-8080}"]
